version: "3"

networks:
  masters:
    external: true

services:
  grpc-csharp:
    image: grpc-csharp
    build:
      context: grpc-csharp
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__GrpcGoServiceUrl: "http://grpc-go:8082"
    ports:
      - "10080:80"
    networks:
      - masters